# Generated by Django 4.2.7 on 2025-03-20 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartorder',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='cartorderitems',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
