# Generated by Django 4.2.7 on 2025-03-20 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_cartorder_options_alter_cartorderitems_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='price',
            new_name='total_amt',
        ),
    ]
